[versions]
agp = "8.9.0"
kotlin = "2.1.0"
ktor = "3.1.0"

[libraries]
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorKotlinxSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin = "io.insert-koin:koin-core-jvm:4.0.2"
appcompat = "androidx.appcompat:appcompat:1.7.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

